PerfectWorldServer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('forum/', include("forum.urls")),
]

handler404 = 'main.views.page_not_found'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path
from forum.views import SectionList, ArticleDetail, SubsectionDetail, add_comment, login_view, \
    logout_view, register, profile

app_name = "forum"
urlpatterns = [
    path("", SectionList.as_view(), name="index"),
    path("article/<int:pk>", ArticleDetail.as_view(), name="article"),
    path("subsection/<int:pk>", SubsectionDetail.as_view(), name="subsection"),
    path("article/<int:article_id>/comment/<int:author_id>", add_comment, name="comment"),
    path("article/<int:article_id>/comment/<int:author_id>/<int:response_to_id>", add_comment, name="response"),
    path("article/<int:article_id>/comment/<int:author_id>/<int:response_to_id>/<int:response_to_author_id>",
         add_comment, name="response_reply"),
    path("login", login_view, name="login"),
    path("logout", logout_view, name="logout"),
    path("register", register, name="register"),
    path("profile/<int:user_id>", profile, name="profile")
]

main/urls.py
from django.urls import path
import main.views as views

app_name = 'main'
urlpatterns = [
   path('', views.index, name='index'),
   path('start_game', views.start_game, name='start_game')
]

handler404 = 'main.views.page_not_found'

forum/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="images/", null=True)


class Section(models.Model):
    name = models.CharField(max_length=180)
    description = models.TextField()

    def __str__(self):
        return self.name


class Subsection(models.Model):
    name = models.CharField(max_length=180)
    description = models.TextField()
    section = models.ForeignKey(Section, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Thread(models.Model):
    # analog of tag
    name = models.CharField(max_length=180)
    priority = models.IntegerField()

    def __str__(self):
        return f"{self.name}, lvl {self.priority}"


class Article(models.Model):
    header = models.CharField(max_length=180)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE, null=True, blank=True)
    subsection = models.ForeignKey(Subsection, on_delete=models.CASCADE)
    thumbnail = models.ImageField(upload_to="images/thumbnails", null=True, blank=True)
    link = models.CharField(max_length=300, null=True)

    def __str__(self):
        return self.header


class Comment(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    response_to = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    response_to_author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="responses",
                                           blank=True)

    def __str__(self):
        return self.text

forum/forms.py
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import password_validation
from django.utils.translation import gettext_lazy as _


class RegisterForm(UserCreationForm):

    error_messages = {
        'password_mismatch': _('Пароли не совпадают'),
    }
    password1 = forms.CharField(
        label=_("Пароль"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text=_("Пароль должен состоять минимум из 8 знаков и включать буквы"),
    )
    password2 = forms.CharField(
        label=_("Подтверждение пароля"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
        help_text=_("Введите тот же пароль"),
    )

    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}

forum/views.py
from django.views import generic
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from forum.forms import RegisterForm
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from forum.models import Section, Subsection, Article, User, Comment
from django.contrib import messages
from online_users.models import OnlineUserActivity


class SectionList(generic.ListView):
    model = Section
    template_name = "forum/index.html"
    context_object_name = "sections"

    def get_context_data(self, **kwargs):
        comments = Comment.objects.order_by("date")
        subsections_count = Subsection.objects.count()
        users_count = User.objects.count()
        new_user = User.objects.order_by('date_joined').last()
        context = super().get_context_data(**kwargs)
        users_online = self.get_online_users()
        context['online_users'] = users_online
        context['online_users_count'] = len(users_online)
        context['comments'] = comments
        context['subsections_count'] = subsections_count
        context['users_count'] = users_count
        context['new_user'] = new_user
        return context

    def get_online_users(self):
        user_activity_objects = OnlineUserActivity.get_user_activities()
        users_online = []
        for user_activity_object in user_activity_objects.all():
            users_online.append(get_object_or_404(User, pk=user_activity_object.pk))
        return users_online


class SubsectionDetail(generic.DeleteView):
    model = Subsection
    template_name = "forum/subsection.html"
    context_object_name = "subsection"


class ArticleDetail(generic.DeleteView):
    model = Article
    template_name = "forum/article.html"
    context_object_name = "article"


def add_comment(request, article_id, author_id, response_to_id=None, response_to_author_id=None):
    article = get_object_or_404(Article, pk=article_id)
    author = get_object_or_404(User, pk=author_id)
    comment = Comment()
    comment.article = article
    comment.author = author
    comment.text = request.POST["text"]
    if response_to_id is not None:
        response_to = get_object_or_404(Comment, pk=response_to_id)
        comment.response_to = response_to
    if response_to_author_id is not None:
        response_to_author = get_object_or_404(User, pk=response_to_author_id)
        comment.response_to_author = response_to_author
    comment.save()
    messages.success(request, f"Комментарий \"{comment}\" добавлен")
    return HttpResponseRedirect(reverse('forum:article', args=(article.id,)))


def login_view(request):
    username = request.POST.get('username', "")
    password = request.POST.get('password', "")
    url_from = request.POST.get("url_from", "/")
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        messages.success(request, "Вы успешно вошли")
        return HttpResponseRedirect(url_from)
    else:
        messages.error(request, "Ошибка входа")
        return HttpResponseRedirect(url_from)


def logout_view(request):
    logout(request)
    messages.success(request, "Вы вышли")
    return HttpResponseRedirect(reverse('forum:index'))


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('forum:index')
    else:
        form = RegisterForm()
    return render(request, 'forum/register.html', {'form': form})


def profile(request, user_id):
    user_profile = get_object_or_404(User, pk=user_id)
    return render(request, "forum/profile.html", context={"user_profile": user_profile})

forum/templates/forum/article.html
{% extends "forum/forum_base.html" %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static "forum/forum.css" %}">
    <link rel="stylesheet" href="{% static "forum/article.css" %}">
{% endblock %}

{% block content %}
<div class="container">
  <div class="list-group mb-3">
    <div class="list-group-item border-white montserrat bg-light-dark">
      <div class="row px-1">
        <div class="col-1 col-half">
            <div class="img-div rounded">
              <img
                src="{{ article.author.userprofile.avatar.url }}"
                class="img-rounded rounded message-avatar"
                alt="{{ article.author.username }}"
              />
            </div>
        </div>
        <div class="col-90 mx-2">
          <h1 class="text-white">{{ article.header }}</h1>
        </div>
      </div>
      <div class="row">
        <p class="text-white">{{ article.text }}</p>
      </div>
      <div class="row justify-content-between">
        <div class="col-3">
            <div class="row">
                <div class="col-5">
                    <p class="text-green font-comment-sm">
                        {{ article.author.username }}
                    </p>
                </div>
                <div class="col-5">
                <p class="text-white font-comment-sm mb-auto mt-auto">
                    {{ article.date }}
                </p>
                </div>
            </div>
        </div>
      </div>
    </div>
    {% if user.is_authenticated %}
    <form class="form-inline" method="post" action="{% url 'forum:comment' article.id user.id %}">
        {% csrf_token %}
      <div class="form-group mb-2 mt-3">
        <div class="row">
          <div class="col-9 col-90">
            <input
              class="form-control"
              name="text"
              id="inputPassword2"
              placeholder="Ответ"
            />
          </div>
          <div class="col-2 col-10">
            <button type="submit" class="btn btn-primary mb-2">Ответить</button>
          </div>
        </div>
      </div>
    </form>
        {% else %}
        <div class="row">
            <p class="text-white mt-3 mb-3">
                <a class="underline hover-green" data-bs-toggle="modal" data-bs-target="#loginModal">Войдите</a>
             или
                <a class="underline hover-green" data-bs-toggle="modal" data-bs-target="#registerModal">зарегистрируйтесь</a>
             чтобы оставить комментарий</p>
        </div>
      {% endif %}
  </div>
  <h5 class="montserrat text-white">Ответы</h5>
  <div class="list-group"></div>
  {% for comment in article.comment_set.all%} {% if not comment.response_to %}
  <div class="list-group-item border-white montserrat bg-light-dark">
    {# comment start #}

    <div class="row px-1">
      <div class="col-sm-1 col-half">
          <div class="img-div-md rounded">
        <img
          src="{{ comment.author.userprofile.avatar.url }}"
          class="img-rounded rounded message-avatar"
          alt="{{ comment.author.username }}"
        />
          </div>
      </div>
      <div class="col-3 col-big">
        <div class="row">
          <p class="montserrat mb-comment font-comment-mid text-green">
            {{ comment.author.username }}
          </p>
        </div>
        <div class="row">
          <p class="text-white mb-comment">{{ comment.text }}</p>
        </div>
        <div class="row justify-content-between">
          <div class="col-3">
            <p class="text-white montserrat mb-comment font-comment-sm">
              {{ comment.date }}
            </p>
          </div>
          <div class="col-1">
              {% if user.is_authenticated %}
          <div class="list-group">
            <a
              href="#list-comment{{ forloop.counter }}"
              class="green-link font-comment-sm collapsed"
              data-bs-toggle="list"
              data-bs-target="#list-comment{{ forloop.counter }}"
              role="button"
              aria-expanded="false"
              aria-controls="list-comment{{ forloop.counter }}"
            >
              Ответить
            </a>
            </div>
                  {% endif %}
          </div>
        </div>
        {% if comment.comment_set %} 
        {% for response in comment.comment_set.all %}
        <hr />
        <div class="row px-3">
          <div class="col-1 col-half">
              <div class="img-div-sm rounded">
                <img
                  src="{{ response.author.userprofile.avatar.url }}"
                  class="img-rounded rounded message-avatar"
                  alt="{{ response.author.username }}"
                />
              </div>
          </div>
          <div class="col-3 col-big">
            <div class="row">
              <p class="montserrat mb-comment font-comment-mid text-green">
                {{ response.author.username }} {% if response.response_to_author %}в ответ {{ response.response_to_author.username }}{% endif %}
              </p>
            </div>
            <div class="row">
              <p class="text-white mb-comment">{{ response.text }}</p>
            </div>
            <div class="row justify-content-between">
              <div class="col-3">
                <p class="text-white montserrat mb-comment font-comment-sm">
                  {{ response.date }}
                </p>
              </div>
              <div class="col-1">
                  {% if user.is_authenticated %}
              <div class="list-group">
                <a
                  href="#collapseResponse{{ forloop.parentcounter }}{{ forloop.counter }}"
                  class="green-link font-comment-sm"
                  data-bs-toggle="list"
                  data-bs-target="#collapseResponse{{ forloop.parentloop.counter }}{{ forloop.counter }}"
                  aria-controls="collapseResponse{{ forloop.parentloop.counter }}{{ forloop.counter }}"
                  role="tab"
                >
                  Ответить
                </a>
                </div>
                  {% endif %}
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        {# Comment response form #}
        <div class="row">
          <div class="tab-content" id="nav-tabContent">
            <div
              class="tab-pane fade"
              id="list-comment{{ forloop.counter }}"
              role="tabpanel"
              aria-labelledby="list-home-list"
            >
                {% if user.is_authenticated %}
              <form class="form-inline" method="post" action="{% url 'forum:response' article.id user.id comment.id %}">
                  {% csrf_token %}
                <div class="form-group mb-2 mt-3">
                  <div class="row">
                    <div class="col-9 col-90">
                      <input
                        class="form-control"
                        name="text"
                        id="inputResponse{{ forloop.counter }}"
                        placeholder="Ответ"
                      />
                    </div>
                    <div class="col-2 col-10">
                      <button type="submit" class="btn btn-primary mb-2">
                        Ответить
                      </button>
                    </div>
                  </div>
                </div>
              </form>
                   {% endif %}
            </div>
          {# Response response form #}
            {% for response in comment.comment_set.all %}
            <div
              class="tab-pane fade"
              id="collapseResponse{{ forloop.parentloop.counter }}{{ forloop.counter }}"
              role="tabpanel"
            >
            {% if user.is_authenticated %}
              <form class="form-inline" method="post" action="{% url 'forum:response_reply' article.id user.id comment.id response.author.id %}">
                  {% csrf_token %}
                <div class="form-group mb-2 mt-3">
                  <div class="row">
                    <div class="col-9 col-90">
                      <input
                        class="form-control"
                        id="inputComment{{ forloop.parentloop.counter }}{{ forloop.counter }}"
                        name="text"
                        value="{{ response.author.username }}, "
                      />
                    </div>
                    <div class="col-2 col-10">
                      <button type="submit" class="btn btn-primary mb-2">
                        Ответить
                      </button>
                    </div>
                  </div>
                </div>
              </form>
            {% endif %}
            </div>
            {% endfor %}
          </div>
        </div>

        {% endif %}
      </div>
    </div>

    {# comment end #}
  </div>
  {% endif %} {% endfor %}
</div>
> {% endblock %}

forum/templates/forum/forum_base.html
{% extends "base.html" %}

{% block nav_battons %}
    {% if user.is_authenticated %}
       <div class="btn-group">
          <a href="{% url 'forum:profile' user.id %}" class="btn colour-green">
              <div class="row align-items-center">
                  <div class="col-7">
                          {{ user.username }}
                  </div>
                  <div class="col-5">
                    <img
                      src="{{ user.userprofile.avatar.url }}"
                      class="img-rounded rounded login-avatar mt-1 mb-1"
                      alt="{{ user.username }}"
                    />
                  </div>
              </div>
          </a>
          <button type="button" class="btn colour-green dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="visually-hidden">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'forum:profile' user.id %}">Личный кабинет</a></li>
            <li><a class="dropdown-item" href="#">Последние посты</a></li>
              <li><a class="dropdown-item" href="#">Редактировать профиль</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'forum:logout' %}">Выйти</a></li>
          </ul>
        </div>
    {% else %}
        <button type="button" data-bs-toggle="modal" data-bs-target="#loginModal" class="btn btn-primary me-2" id="login-nav">Вход</button>
        <a href="{% url 'forum:register' %}" class="btn btn-primary">Регистрация</a>
    {% endif %}
{% endblock %}
{% block modal %}
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content bg-dark">
        <div class="modal-header">
           <h2 class="text-white">Вход</h2>
        </div>
        <div class="modal-body">
        <form method="post" action="{% url "forum:login" %}">{% csrf_token %}
          <div class="form-group">
            <label for="exampleInputEmail1" class="montserrat mb-2 text-white">Имя пользователя</label>
            <input  type="text" class="form-control mb-2 montserrat" name="username" id="login_username" placeholder="Имя пользователя">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1" class="montserrat mb-2 text-white">Пароль</label>
            <input type="password" class="form-control mb-2 montserrat" name="password" id="login_password" placeholder="Пароль">
          </div>
            <input type="text" name="url_from" value="{{ request.path }}" style="display: none">
          <button type="submit" class="btn btn-primary text-white">Войти</button>
        </form>
        </div>
    </div>
  </div>
</div>

<div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content bg-dark">
        <div class="modal-header">
           <h2 class="text-white">Регистрация</h2>
        </div>
        <div class="modal-body">
        <form method="post" action="{% url 'forum:register' %}">{% csrf_token %}
          <div class="form-group">
            <label for="exampleInputEmail1" class="montserrat mb-2 text-white">Имя пользователя</label>
            <input class="form-control mb-2 montserrat" name="username" id="register_username" placeholder="Имя пользователя">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1" class="montserrat mb-2 text-white">Пароль</label>
            <input type="password" class="form-control mb-2 montserrat" name="password" id="register_password" placeholder="Пароль">
          </div>
            <div class="form-group">
            <label for="exampleInputPassword1" class="montserrat mb-2 text-white">Пароль</label>
            <input type="password" class="form-control mb-2 montserrat" name="password_repeat" id="register_password" placeholder="Пароль еще раз">
          </div>
            <input type="text" name="url_from" value="{{ request.path }}" style="display: none">
          <button type="submit" class="btn btn-primary text-white">Войти</button>
        </form>
        </div>
    </div>
  </div>
</div>
{% endblock %}

forum/templates/forum/profile.html
{% extends "forum/forum_base.html" %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static "forum/forum.css" %}">
    <link rel="stylesheet" href="{% static "forum/article.css" %}">
{% endblock %}

{% block content %}
    <div class="container">
    <div class="row">
        <div class="col-3">
                <img
                  src="{{ user.userprofile.avatar.url }}"
                  class="rounded profile-avatar mx-auto d-block"
                  alt="{{ user.username }}"
                />
            <h2 class="text-center text-white mt-3 montserrat">{{ user.username }}</h2>
        </div>
        <div class="col-7 align-content-center">
            <div class="row">
                <div class="list-group list-group-horizontal mb-3 p-2" id="list-tab" role="tablist">
                  <a class="list-group-item list-group-item-action active" id="list-articles-list" data-bs-toggle="list" href="#list-articles" role="tab" aria-controls="home">Статьи</a>
                  <a class="list-group-item list-group-item-action" id="list-profile-list" data-bs-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Комментарии</a>
                  <a class="list-group-item list-group-item-action" id="list-messages-list" data-bs-toggle="list" href="#list-messages" role="tab" aria-controls="messages">Messages</a>
                  <a class="list-group-item list-group-item-action" id="list-settings-list" data-bs-toggle="list" href="#list-settings" role="tab" aria-controls="settings">Settings</a>
              </div>
                <div class="tab-content p-2" id="nav-tabContent">
                  <div class="tab-pane fade show active" id="list-articles" role="tabpanel" aria-labelledby="list-articles-list">
                      {% for article in user_profile.article_set.all %}
                          <div class="list-group-item border-white montserrat bg-light-dark">
                          <div class="row">
                            <div class="col-90">
                              <a href="{% url "forum:article" article.id %}" class="green-link h1">{{ article.header }}</a>
                            </div>
                          </div>
                          <div class="row">
                            <p class="text-white">{{ article.text }}</p>
                          </div>
                          <div class="row justify-content-between">
                            <div class="col-6">
                                <div class="row">
                                    <div class="col-5">
                                        <p class="text-green font-comment-sm">
                                            {{ article.author.username }}
                                        </p>
                                    </div>
                                    <div class="col-5">
                                    <p class="text-white font-comment-sm mb-auto mt-auto">
                                        {{ article.date }}
                                    </p>
                                    </div>
                                </div>
                            </div>
                          </div>
                        </div>
                      {% endfor %}
                  </div>
                  <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">
                      {% for comment in user_profile.comment_set.all %}
                              <div class="list-group-item border-white montserrat bg-light-dark">
                                 <div class="row px-1">
                                  <div class="col-sm-1 col-half">
                                    <img
                                      src="{{ comment.author.userprofile.avatar.url }}"
                                      class="img-rounded rounded message-avatar"
                                      alt="{{ article.author.username }}"
                                    />
                                  </div>
                                  <div class="col-3 col-big">
                                    <div class="row">
                                      <p class="montserrat mb-comment font-comment-mid text-green">
                                        {{ comment.author.username }}
                                      </p>
                                    </div>
                                    <div class="row">
                                      <a href="{% url 'forum:article' comment.article.id %}" class="green-link mb-comment">{{ comment.text }}</a>
                                    </div>
                                    <div class="row justify-content-between">
                                      <div class="col-3">
                                        <p class="text-white montserrat mb-comment font-comment-sm">
                                          {{ comment.date }}
                                        </p>
                                      </div>
{#                                      <div class="col-1">#}
{#                                          {% if user.is_authenticated %}#}
{#                                      <div class="list-group">#}
{#                                        <a#}
{#                                          href="#list-comment{{ forloop.counter }}"#}
{#                                          class="green-link font-comment-sm collapsed"#}
{#                                          data-bs-toggle="list"#}
{#                                          data-bs-target="#list-comment{{ forloop.counter }}"#}
{#                                          role="button"#}
{#                                          aria-expanded="false"#}
{#                                          aria-controls="list-comment{{ forloop.counter }}"#}
{#                                        >#}
{#                                          Ответить#}
{#                                        </a>#}
{#                                        </div>#}
{#                                              {% endif %}#}
{#                                      </div>#}
                                    </div>
                              </div>
                                 </div>
                              </div>
                          {% endfor %}
                  </div>
                  <div class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">...</div>
                  <div class="tab-pane fade" id="list-settings" role="tabpanel" aria-labelledby="list-settings-list">...</div>
                </div>
            </div>
        </div>
            </div>
    </div>
{% endblock %}

forum/templates/forum/subsection.html
{% extends "forum/forum_base.html" %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static "forum/forum.css" %}">
{%  endblock %}

{% block content %}
    <div class="container">
    <h2 class="text-white montserrat">{{ subsection.name }}</h2>
    <p class="text-white montserrat"> {{ subsection.description }} </p>
        <div class="list-group">
        {% for article in subsection.article_set.all%}
            <div class="list-group-item border-white montserrat bg-light-dark">
              <div class="row">
              <div class="col-1 text-white">
                  <div class="d-flex h-100 justify-content-start align-items-center">
                    <h4>{{ article.comment_set.count }}</h4>
                  </div>
              </div>
               <div class="col">
                   <div class="d-flex h-100 justify-content-start align-items-center">
                   <a class="green-link" href="{% url "forum:article" article.id %}">
                  <h5 class="mb-1">{{ article.header }}</h5>
                   </a>
                   </div>
               </div>
                  <div class="col">
               <div class="d-flex justify-content-end align-items-center h-100">
                   <div class="dropdown">
                       <a href="#" class="white hover-green" id="dropdownMenuButton{{ forloop.counter }}" data-bs-toggle="dropdown" aria-expanded="false">
                       <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
                          <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                        </svg>
                       </a>
                       <div class="dropdown-menu" role="menu" aria-labelledby="dropdownMenuButton{{ forloop.counter }}">
                        <a class="dropdown-item" href="#">Ответить</a>
                      </div>
                   </div>
               </div>
                  </div>
                  {% if subsection.article_set.last.author.avatar %}
                      <div class="col-1">
                        <img src="{{ article.author.avatar.url }}" class="img-rounded img-avatar" alt="{{ article.author.nick }}">
                      </div>
                  {% endif %}
               <div class="col-2">

                   <div class="row white">
                       {{ article.author.nick }}
                   </div>
                   <div class="row white">
                       {{ article.date }}
                   </div>
               </div>
              </div>
              </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}