PerfectWorldServer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('forum/', include("forum.urls")),
]

handler404 = 'main.views.page_not_found'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
import main.views as views

app_name = 'main'
urlpatterns = [
   path('', views.index, name='index'),
   path('start_game', views.start_game, name='start_game')
]

handler404 = 'main.views.page_not_found'

templates/base.html
<!DOCTYPE html>
<html lang="en" class="bg-dark">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- CSS only -->
{#    {% load sass_tags %}#}
    {% load static %}
{#    <link href="{% sass_src 'main.css' %}" rel="stylesheet" type="text/css" />#}
    <link href="{% static 'main.css' %}" rel="stylesheet" type="text/css" />
{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">#}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static "main/css/main.css" %}">
    {% block static %}
    {% endblock %}
    {% block meta %}
    {% endblock %}
</head>
<body class="bg-dark">
{# Header #}
<header class="p-3 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <!-- <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi me-2 bi-joystick" width="32" height="32" viewBox="0 0 16 16">
                <path d="M10 2a2 2 0 0 1-1.5 1.937v5.087c.863.083 1.5.377 1.5.726 0 .414-.895.75-2 .75s-2-.336-2-.75c0-.35.637-.643 1.5-.726V3.937A2 2 0 1 1 10 2z"/>
                <path d="M0 9.665v1.717a1 1 0 0 0 .553.894l6.553 3.277a2 2 0 0 0 1.788 0l6.553-3.277a1 1 0 0 0 .553-.894V9.665c0-.1-.06-.19-.152-.23L9.5 6.715v.993l5.227 2.178a.125.125 0 0 1 .001.23l-5.94 2.546a2 2 0 0 1-1.576 0l-5.94-2.546a.125.125 0 0 1 .001-.23L6.5 7.708l-.013-.988L.152 9.435a.25.25 0 0 0-.152.23z"/>
            </svg>
      </a> -->

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="http://constantapw.ru/" class="px-2 text-white lovelace navbar-brand">
          <img src="{% static 'main/img/logo.png' %}" class="logo" alt="logo">
        </a></li>
        <li><a {% block about_link %}{% endblock %} class="nav-link px-2 text-white" id="about-server-btn">О сервере</a></li>
        <li><a href="{% url 'main:start_game' %}" class="nav-link px-2 text-white">Начать игру</a></li>
          {% block forum_link %}
          <li><a href="https://forum.constantapw.ru/index.php" class="nav-link px-2 text-white">Форум</a></li>
          {% endblock %}
        <li><a href="https://forum.constantapw.ru/index.php?threads/Пожертвования-проекту.77/" class="nav-link px-2 text-white">Пожертвовать</a></li>
        <li class="d-flex">
          <a href="https://pw.mmotop.ru/servers/35115" class="d-flex align-items-center ms-4 mb-auto mt-auto mx-2 text-white text-decoration-none">
            <img src="{% static 'main/img/mmotop.svg' %}" width="32" height="32" alt="MMOTOP">
          </a>
        </li>
        <li class="d-flex">
          <a href="https://vk.com/constanta_pw" class="d-flex align-items-center mb-auto mt-auto mx-2 text-white text-decoration-none">
            <img src="{% static 'main/img/tlg.svg' %}" width="16" height="16" alt="Telegram">
          </a> 
        </li>
        <li class="d-flex">
          <a href="https://vk.com/constanta_pw" class="d-flex align-items-center mb-auto mt-auto mx-2 text-white text-decoration-none">
            <img src="{% static 'main/img/vk.svg' %}" width="16" height="16" alt="VK">
          </a>
        </li>
      </ul>
        {% block nav_battons %}
        <a href="https://cp.constantapw.ru" class="btn btn-primary me-2 golden-button" id="login-nav">Личный кабинет</a>
        <!-- <button type="button" class="btn btn-primary" id="register-nav">Регистрация</button> -->
        {% endblock %}
    </div>
  </div>
</header>
<main class="bg-dark">
{% block content %}
{% endblock %}
{% block modal %}
{% endblock %}

{# messages #}
{% if messages %}
<div class="position-fixed bottom-0 mb-5 end-0 p-3" style="z-index: 5">
{% for message in messages %}
  <div id="toast{{ forloop.counter }}" class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
      <strong class="me-auto">Constanta</strong>
      <button id="closeToast{{ forloop.counter }}" type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    </div>
  </div>
{% endfor %}
</div>
{% endif %}
</main>
<nav class="footer navbar navbar-dark bg-dark mt-auto">
<hr class="mx-4 mt-5">
  <div class="d-flex container text-white justify-content-start mt-2 px-0">
      <div class="col-6">
        <div class="col-10 justify-content-start">
          <ul class="nav mb-2 justify-content-start">
          <li>
            <a class="nav-link text-white ps-0" href="#">О сервере</a>
          </li>
          <li>
            <a class="nav-link text-white ps-0" href="{% url 'main:start_game' %}">Начать игру</a>
          </li>
           <li>
            <a class="nav-link text-white ps-0" href="https://forum.constantapw.ru/index.php">Форум</a>
          </li>
        </ul>
        </div>
      </div>
      <div class="col-5">
        <div class="row align-bottom justify-content-end">
          <div class="col-6">
          <ul class="nav mb-3 justify-content-evenly">
            <li class="d-flex mt-2">
              <a href="https://pw.mmotop.ru/servers/35115" class="d-flex align-items-center ms-4 mb-auto mt-auto mx-2 text-white text-decoration-none">
                <img src="{% static 'main/img/mmotop.svg' %}" width="32" height="32" alt="MMOTOP">
              </a>
            </li>
            <li class="d-flex mt-2">
              <a href="#" class="d-flex align-items-center mb-auto mt-auto mx-2 text-white text-decoration-none">
                <img src="{% static 'main/img/tlg.svg' %}" width="16" height="16" alt="Telegram">
              </a> 
            </li>
            <li class="d-flex mt-2">
              <a href="https://vk.com/constanta_pw" class="d-flex align-items-center mb-auto mt-auto mx-2 text-white text-decoration-none">
                <img src="{% static 'main/img/vk.svg' %}" width="16" height="16" alt="VK">
              </a>
            </li>
          </ul>
        </div> 
        <div class="col-2">
          <ul class="nav mb-2 mt-1 justify-content-end">
            <li class="lovelace">
              <img src="{% static 'main/img/logo.png' %}" class="logo" alt="logo">
            </li>
          </ul>
        </div>
        </div>
    </div> 
  </div>
  
</nav>
</body>

{% if messages %}
    {% for message in messages %}
<script>
button{{ forloop.counter }} = document.getElementById("closeToast{{ forloop.counter }}")
button{{ forloop.counter }}.onclick = function() {
    $('#toast{{ forloop.counter }}').toast('hide')
}
</script>
    {% endfor %}
{% endif %}
</html>